/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthenticatedDealerRouteImport } from './routes/_authenticated/dealer'
import { Route as AuthenticatedMyProductsRouteImport } from './routes/_authenticated/my-products'
import { Route as AuthenticatedRegisterProductRouteImport } from './routes/_authenticated/register-product'
import { Route as AuthenticatedProductIdRouteImport } from './routes/_authenticated/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDealerRoute = AuthenticatedDealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProductsRoute = AuthenticatedMyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegisterProductRoute =
  AuthenticatedRegisterProductRouteImport.update({
    id: '/register-product',
    path: '/register-product',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductIdRoute = AuthenticatedProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dealer': typeof AuthenticatedDealerRoute
  '/my-products': typeof AuthenticatedMyProductsRoute
  '/register-product': typeof AuthenticatedRegisterProductRoute
  '/product/$id': typeof AuthenticatedProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dealer': typeof AuthenticatedDealerRoute
  '/my-products': typeof AuthenticatedMyProductsRoute
  '/register-product': typeof AuthenticatedRegisterProductRoute
  '/product/$id': typeof AuthenticatedProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/_authenticated/dealer': typeof AuthenticatedDealerRoute
  '/_authenticated/my-products': typeof AuthenticatedMyProductsRoute
  '/_authenticated/register-product': typeof AuthenticatedRegisterProductRoute
  '/_authenticated/product/$id': typeof AuthenticatedProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dealer'
    | '/my-products'
    | '/register-product'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dealer'
    | '/my-products'
    | '/register-product'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard'
    | '/_authenticated/dealer'
    | '/_authenticated/my-products'
    | '/_authenticated/register-product'
    | '/_authenticated/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dealer': {
      id: '/_authenticated/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof AuthenticatedDealerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-products': {
      id: '/_authenticated/my-products'
      path: '/my-products'
      fullPath: '/my-products'
      preLoaderRoute: typeof AuthenticatedMyProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register-product': {
      id: '/_authenticated/register-product'
      path: '/register-product'
      fullPath: '/register-product'
      preLoaderRoute: typeof AuthenticatedRegisterProductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product/$id': {
      id: '/_authenticated/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AuthenticatedProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDealerRoute: typeof AuthenticatedDealerRoute
  AuthenticatedMyProductsRoute: typeof AuthenticatedMyProductsRoute
  AuthenticatedRegisterProductRoute: typeof AuthenticatedRegisterProductRoute
  AuthenticatedProductIdRoute: typeof AuthenticatedProductIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDealerRoute: AuthenticatedDealerRoute,
  AuthenticatedMyProductsRoute: AuthenticatedMyProductsRoute,
  AuthenticatedRegisterProductRoute: AuthenticatedRegisterProductRoute,
  AuthenticatedProductIdRoute: AuthenticatedProductIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
